Started feed_me
peter-maria-play-org/side_projects pull request #1
Opened 2024-10-03 17:32 UTC by peterkaloyannis

Started the feed_me project!

2024-10-05 16:16 UTC, mnavarrocastillo commented on feed_me/feed_me/task_manager.py
> +        # Loop through the sorted indices, returning the n_tasks
i dont like you

2024-10-14 23:27 UTC, mnavarrocastillo requested changes
I request changes
Also, please help me to set this up and edit in VS

2024-10-14 23:27 UTC, mnavarrocastillo commented on .gitignore
> +.ruff_cache
why?

2024-10-14 23:27 UTC, mnavarrocastillo commented on README.md
> +undertaken by Peter Kaloyannis and Maria Fernanda Navarro Castillo.
Change my name to Maria Navarro

2024-10-14 23:27 UTC, mnavarrocastillo commented on README.md
> +This repository is built upon the pupular [UV](https://github.com/astral-sh/uv)
popular

2024-10-14 23:27 UTC, mnavarrocastillo commented on feed_me/feed_me/task_manager.py
> +    deadline. They also form the basis of
the basis of?

2024-10-15 00:45 UTC, pkaloyannis-cfs commented on README.md
> +undertaken by Peter Kaloyannis and Maria Fernanda Navarro Castillo.
Done

2024-10-15 00:45 UTC, pkaloyannis-cfs commented on README.md
> +This repository is built upon the pupular [UV](https://github.com/astral-sh/uv)
Nice catch. Done

2024-10-15 00:53 UTC, peterkaloyannis commented
> I request changes Also, please help me to set this up and edit in VS

If I have done my job writing the README.md properly, you should not need assistance. I added a bit more to it so that you could see it.

2024-10-15 01:08 UTC, pkaloyannis-cfs commented on .gitignore
> +.ruff_cache
I deleted most of the other stuff, which was created by github by default. Having a bigger file is just more code to maintain, and so its usually better to build the .gitignore file incrementally with your codebase.

The specific things you are asking about are some temporary files created by vscode and by python when you run it. They are not real code, just useful things your computer uses when you are running scripts.

2024-10-15 01:39 UTC, peterkaloyannis commented on feed_me/feed_me/task_manager.py
> +    deadline. They also form the basis of
nice catch. fixed.

2024-10-15 02:19 UTC, mnavarrocastillo approved these changes
Good job

2024-10-15 02:20 UTC, merged